### ISSUE TITLE
No click module even when it's installed

### ISSUE THREAD

**Issue by sxiii** [zdave/openconnect-gp-okta#11]
Hi! Trying to run your script:

```
[sm@localhost openconnect-gp-okta]$ python openconnect-gp-okta 
Traceback (most recent call last):
  File "/home/sm/openconnect-gp-okta/openconnect-gp-okta", line 4, in <module>
    import click
ModuleNotFoundError: No module named 'click'
[sm@localhost openconnect-gp-okta]$ pythonw openconnect-gp-okta 
bash: pythonw: command not found...
Similar command is: 'python'
[sm@localhost openconnect-gp-okta]$ python3 openconnect-gp-okta 
Traceback (most recent call last):
  File "/home/sm/openconnect-gp-okta/openconnect-gp-okta", line 4, in <module>
    import click
ModuleNotFoundError: No module named 'click'
[sm@localhost openconnect-gp-okta]$ pip3 install click
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: click in /home/sm/.local/lib/python3.6/site-packages (7.1.2)
WARNING: You are using pip version 21.1.2; however, version 21.1.3 is available.
You should consider upgrading via the '/usr/bin/python3.6 -m pip install --upgrade pip' command.
```

Any ideas? :)

**Comment by zdave** [comment]
What is the output of `python3 --version`? And `python3 -c 'import sys; print(sys.path)'`?
